// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ocrosby/golab/mocking/cars/honda (interfaces: IAccordBuilder)

// Package honda is a generated GoMock package.
package honda

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAccordBuilder is a mock of IAccordBuilder interface.
type MockIAccordBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockIAccordBuilderMockRecorder
}

// MockIAccordBuilderMockRecorder is the mock recorder for MockIAccordBuilder.
type MockIAccordBuilderMockRecorder struct {
	mock *MockIAccordBuilder
}

// NewMockIAccordBuilder creates a new mock instance.
func NewMockIAccordBuilder(ctrl *gomock.Controller) *MockIAccordBuilder {
	mock := &MockIAccordBuilder{ctrl: ctrl}
	mock.recorder = &MockIAccordBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccordBuilder) EXPECT() *MockIAccordBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockIAccordBuilder) Build() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Build")
}

// Build indicates an expected call of Build.
func (mr *MockIAccordBuilderMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockIAccordBuilder)(nil).Build))
}

// BuildState mocks base method.
func (m *MockIAccordBuilder) BuildState(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildState", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildState indicates an expected call of BuildState.
func (mr *MockIAccordBuilderMockRecorder) BuildState(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildState", reflect.TypeOf((*MockIAccordBuilder)(nil).BuildState), arg0)
}

// BuildYear mocks base method.
func (m *MockIAccordBuilder) BuildYear(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildYear", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildYear indicates an expected call of BuildYear.
func (mr *MockIAccordBuilderMockRecorder) BuildYear(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildYear", reflect.TypeOf((*MockIAccordBuilder)(nil).BuildYear), arg0)
}

// GetInstance mocks base method.
func (m *MockIAccordBuilder) GetInstance() *Accord {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance")
	ret0, _ := ret[0].(*Accord)
	return ret0
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockIAccordBuilderMockRecorder) GetInstance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockIAccordBuilder)(nil).GetInstance))
}
