// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ocrosby/golab/mocking (interfaces: Automobile)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockAutomobile is a mock of Automobile interface.
type MockAutomobile struct {
	ctrl     *gomock.Controller
	recorder *MockAutomobileMockRecorder
}

// MockAutomobileMockRecorder is the mock recorder for MockAutomobile.
type MockAutomobileMockRecorder struct {
	mock *MockAutomobile
}

// NewMockAutomobile creates a new mock instance.
func NewMockAutomobile(ctrl *gomock.Controller) *MockAutomobile {
	mock := &MockAutomobile{ctrl: ctrl}
	mock.recorder = &MockAutomobileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutomobile) EXPECT() *MockAutomobileMockRecorder {
	return m.recorder
}
